name: GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6
          
      
      - name: Run test with pytest 
        run: |
          pip install pytest
          pytest
          
         
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov 
          

      - name: Tests and coverage
        run: |
          coverage xml -i -o coverage-xml
     
      - name: Test Report
        run: coverage report 




          

