name: GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
          pip install pytest pytest-cov 
          
      
      - name: Run test with pytest 
        run: |
          pip install pytest
          pytest
      - name: Download ChromeDriver
        run: |
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.159/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
    
      - name: Set Permissions for ChromeDriver
        run: |
          chmod +x chromedriver-linux64 

      - name: Tests and coverage
        run: |
          coverage run -m pytest
          coverage xml -i -o coverage-xml
     
      - name: Test Report
        run: coverage report 




          

