name: GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
          pip install pytest pytest-cov
      
      - name: Update pytest and py
        run: |
              pip install --upgrade pytest py
      - name: Print requirements.txt
        run: cat requirements.txt

      - name: Print current directory
        run: |
              pwd && ls -l

      - name: Generate coverage
        run: |
          coverage run -m pytest src/tests
          coverage xml -i -o coverage.xml

          
      - name: Coverage report
        run: |
          coverage report

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
