name: GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
          pip install pytest pytest-cov
          pip install behave
          
      
      - name: Update pytest and py
        run: |
              pip install --upgrade pytest py
      - name: Print requirements.txt
        run: cat requirements.txt

        
    # Run set of commands unit tests and sonar cloud
      - name: Run tests with coverage
        run: |
          coverage run -m pytest src/tests
          coverage xml -i -o coverage.xml


          
      - name: Coverage report
        run: |
          coverage report

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
     
     # Run  ATDD
     
      - name: Download ChromeDriver
        run: |
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.159/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
    
      - name: Set Permissions for ChromeDriver
        run: |
          chmod +x chromedriver-linux64
          
      - name: Run Test
        if: always()
        run: |
          behave -f allure_behave.formatter:AllureFormatter -o reports -vv automation-test/features 
          continue-on-error: true

        
      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: allure-reports
          path: allure-reports

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1
        if: always()
        with:
          allure_results: reports
          allure_history: reports
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: allure-reports
          PUBLISH_DIR: reports
